# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '抽屉效果' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for 抽屉效果
  
  pod 'GPUImage', '~> 0.1.7'
  pod 'Masonry', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.3.1'
  pod 'SDWebImage', '~> 5.4.0'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'SVProgressHUD', '~> 2.2.5'

end
